export interface IOrder {
    orderId?: number; // optional because it will be generated by API
    customerId: number;
    productId: number;
    receiverName: string;
    receiverPhoneNo: string;
    shippingAddress?: string;
    orderDate?: Date; // optional, set by backend
}
